# Generated by Django 3.2 on 2022-06-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nossareservaapp', '0002_alter_condominio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomum',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='arealocacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
    ]
