# Generated by Django 3.2 on 2022-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossareservaapp', '0004_alter_arealocacao_nome_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='criacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
